# Generated by Django 3.1.4 on 2020-12-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='background',
            field=models.CharField(default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='extra_requirements',
            field=models.TextField(blank=True, default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='text_color',
            field=models.CharField(default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='text_content',
            field=models.TextField(default='add your text', max_length=20),
        ),
    ]
