# Generated by Django 3.1.4 on 2020-12-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
