# Generated by Django 3.1.4 on 2020-12-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personalise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(editable=False, max_length=32)),
                ('background', models.CharField(choices=[('standard', 'standard as sample'), ('simplify', 'less elements'), ('elaborate', 'more elements')], default='standard', max_length=10)),
                ('text_color', models.CharField(choices=[('standard', 'standard as sample'), ('golden', 'golden tone'), ('silver', 'silverish tone')], default='standard', max_length=10)),
                ('text_content', models.TextField(max_length=20)),
                ('extra_requirements', models.TextField(max_length=255)),
            ],
        ),
    ]
