# Generated by Django 3.1.4 on 2020-12-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalise',
            name='extra_requirements',
            field=models.TextField(blank=True, default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalise',
            name='text_content',
            field=models.TextField(default='add your text', max_length=20),
        ),
    ]
