# Generated by Django 3.1.4 on 2020-12-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0003_personalise_cost_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalise',
            name='background',
            field=models.CharField(choices=[('standard', 'standard as sample'), ('simplify', 'less elements'), ('elaborate', 'more elements + £ 5.00')], default='standard', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalise',
            name='extra_requirements',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalise',
            name='text_content',
            field=models.TextField(max_length=20),
        ),
    ]
